"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import { AppProvider, useGlobalContext } from "../../context/Context";
import NavBar from "../../components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Task Manager",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} relative`}>
        <AppProvider>
          <header className="bg-[#E5D1F2]">
            <NavBar />
          </header>
          {children}
        </AppProvider>
      </body>
    </html>
  );
}
